name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{runner.os}}-npm-${{hashFiles('package-lock.json')}}

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1
      
      - name: Deploy dist to AWS S3
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: ${{secrets.AWS_DEFAULT_REGION}}
          AWS_DEFAULT_OUTPUT: json
        run: |
          aws s3 sync ./dist s3://${{secrets.AWS_BUCKET_NAME}}/web-john/
